package io.github.deathbeam.discordgamesdk;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.PointerByReference;
import io.github.deathbeam.discordgamesdk.IDiscordCore.ByReference;
/**
 * JNA Wrapper for library <b>discord_game_sdk</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface DiscordGameSDK extends Library {
	public static final String JNA_LIBRARY_NAME = "discord_game_sdk";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(DiscordGameSDK.JNA_LIBRARY_NAME);
	public static final DiscordGameSDK INSTANCE = (DiscordGameSDK)Native.loadLibrary(DiscordGameSDK.JNA_LIBRARY_NAME, DiscordGameSDK.class);
	/**
	 * <i>native declaration : discord_game_sdk.h:25</i><br>
	 * enum values
	 */
	public static interface EDiscordResult {
		/** <i>native declaration : discord_game_sdk.h:26</i> */
		public static final int DiscordResult_Ok = 0;
		/** <i>native declaration : discord_game_sdk.h:27</i> */
		public static final int DiscordResult_ServiceUnavailable = 1;
		/** <i>native declaration : discord_game_sdk.h:28</i> */
		public static final int DiscordResult_InvalidVersion = 2;
		/** <i>native declaration : discord_game_sdk.h:29</i> */
		public static final int DiscordResult_LockFailed = 3;
		/** <i>native declaration : discord_game_sdk.h:30</i> */
		public static final int DiscordResult_InternalError = 4;
		/** <i>native declaration : discord_game_sdk.h:31</i> */
		public static final int DiscordResult_InvalidPayload = 5;
		/** <i>native declaration : discord_game_sdk.h:32</i> */
		public static final int DiscordResult_InvalidCommand = 6;
		/** <i>native declaration : discord_game_sdk.h:33</i> */
		public static final int DiscordResult_InvalidPermissions = 7;
		/** <i>native declaration : discord_game_sdk.h:34</i> */
		public static final int DiscordResult_NotFetched = 8;
		/** <i>native declaration : discord_game_sdk.h:35</i> */
		public static final int DiscordResult_NotFound = 9;
		/** <i>native declaration : discord_game_sdk.h:36</i> */
		public static final int DiscordResult_Conflict = 10;
		/** <i>native declaration : discord_game_sdk.h:37</i> */
		public static final int DiscordResult_InvalidSecret = 11;
		/** <i>native declaration : discord_game_sdk.h:38</i> */
		public static final int DiscordResult_InvalidJoinSecret = 12;
		/** <i>native declaration : discord_game_sdk.h:39</i> */
		public static final int DiscordResult_NoEligibleActivity = 13;
		/** <i>native declaration : discord_game_sdk.h:40</i> */
		public static final int DiscordResult_InvalidInvite = 14;
		/** <i>native declaration : discord_game_sdk.h:41</i> */
		public static final int DiscordResult_NotAuthenticated = 15;
		/** <i>native declaration : discord_game_sdk.h:42</i> */
		public static final int DiscordResult_InvalidAccessToken = 16;
		/** <i>native declaration : discord_game_sdk.h:43</i> */
		public static final int DiscordResult_ApplicationMismatch = 17;
		/** <i>native declaration : discord_game_sdk.h:44</i> */
		public static final int DiscordResult_InvalidDataUrl = 18;
		/** <i>native declaration : discord_game_sdk.h:45</i> */
		public static final int DiscordResult_InvalidBase64 = 19;
		/** <i>native declaration : discord_game_sdk.h:46</i> */
		public static final int DiscordResult_NotFiltered = 20;
		/** <i>native declaration : discord_game_sdk.h:47</i> */
		public static final int DiscordResult_LobbyFull = 21;
		/** <i>native declaration : discord_game_sdk.h:48</i> */
		public static final int DiscordResult_InvalidLobbySecret = 22;
		/** <i>native declaration : discord_game_sdk.h:49</i> */
		public static final int DiscordResult_InvalidFilename = 23;
		/** <i>native declaration : discord_game_sdk.h:50</i> */
		public static final int DiscordResult_InvalidFileSize = 24;
		/** <i>native declaration : discord_game_sdk.h:51</i> */
		public static final int DiscordResult_InvalidEntitlement = 25;
		/** <i>native declaration : discord_game_sdk.h:52</i> */
		public static final int DiscordResult_NotInstalled = 26;
		/** <i>native declaration : discord_game_sdk.h:53</i> */
		public static final int DiscordResult_NotRunning = 27;
		/** <i>native declaration : discord_game_sdk.h:54</i> */
		public static final int DiscordResult_InsufficientBuffer = 28;
		/** <i>native declaration : discord_game_sdk.h:55</i> */
		public static final int DiscordResult_PurchaseCanceled = 29;
		/** <i>native declaration : discord_game_sdk.h:56</i> */
		public static final int DiscordResult_InvalidGuild = 30;
		/** <i>native declaration : discord_game_sdk.h:57</i> */
		public static final int DiscordResult_InvalidEvent = 31;
		/** <i>native declaration : discord_game_sdk.h:58</i> */
		public static final int DiscordResult_InvalidChannel = 32;
		/** <i>native declaration : discord_game_sdk.h:59</i> */
		public static final int DiscordResult_InvalidOrigin = 33;
		/** <i>native declaration : discord_game_sdk.h:60</i> */
		public static final int DiscordResult_RateLimited = 34;
		/** <i>native declaration : discord_game_sdk.h:61</i> */
		public static final int DiscordResult_OAuth2Error = 35;
		/** <i>native declaration : discord_game_sdk.h:62</i> */
		public static final int DiscordResult_SelectChannelTimeout = 36;
		/** <i>native declaration : discord_game_sdk.h:63</i> */
		public static final int DiscordResult_GetGuildTimeout = 37;
		/** <i>native declaration : discord_game_sdk.h:64</i> */
		public static final int DiscordResult_SelectVoiceForceRequired = 38;
		/** <i>native declaration : discord_game_sdk.h:65</i> */
		public static final int DiscordResult_CaptureShortcutAlreadyListening = 39;
		/** <i>native declaration : discord_game_sdk.h:66</i> */
		public static final int DiscordResult_UnauthorizedForAchievement = 40;
		/** <i>native declaration : discord_game_sdk.h:67</i> */
		public static final int DiscordResult_InvalidGiftCode = 41;
		/** <i>native declaration : discord_game_sdk.h:68</i> */
		public static final int DiscordResult_PurchaseError = 42;
		/** <i>native declaration : discord_game_sdk.h:69</i> */
		public static final int DiscordResult_TransactionAborted = 43;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:72</i><br>
	 * enum values
	 */
	public static interface EDiscordCreateFlags {
		/** <i>native declaration : discord_game_sdk.h:73</i> */
		public static final int DiscordCreateFlags_Default = 0;
		/** <i>native declaration : discord_game_sdk.h:74</i> */
		public static final int DiscordCreateFlags_NoRequireDiscord = 1;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:77</i><br>
	 * enum values
	 */
	public static interface EDiscordLogLevel {
		/** <i>native declaration : discord_game_sdk.h:78</i> */
		public static final int DiscordLogLevel_Error = 1;
		/** <i>native declaration : discord_game_sdk.h:79</i> */
		public static final int DiscordLogLevel_Warn = 2;
		/** <i>native declaration : discord_game_sdk.h:80</i> */
		public static final int DiscordLogLevel_Info = 3;
		/** <i>native declaration : discord_game_sdk.h:81</i> */
		public static final int DiscordLogLevel_Debug = 4;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:84</i><br>
	 * enum values
	 */
	public static interface EDiscordUserFlag {
		/** <i>native declaration : discord_game_sdk.h:85</i> */
		public static final int DiscordUserFlag_Partner = 2;
		/** <i>native declaration : discord_game_sdk.h:86</i> */
		public static final int DiscordUserFlag_HypeSquadEvents = 4;
		/** <i>native declaration : discord_game_sdk.h:87</i> */
		public static final int DiscordUserFlag_HypeSquadHouse1 = 64;
		/** <i>native declaration : discord_game_sdk.h:88</i> */
		public static final int DiscordUserFlag_HypeSquadHouse2 = 128;
		/** <i>native declaration : discord_game_sdk.h:89</i> */
		public static final int DiscordUserFlag_HypeSquadHouse3 = 256;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:92</i><br>
	 * enum values
	 */
	public static interface EDiscordPremiumType {
		/** <i>native declaration : discord_game_sdk.h:93</i> */
		public static final int DiscordPremiumType_None = 0;
		/** <i>native declaration : discord_game_sdk.h:94</i> */
		public static final int DiscordPremiumType_Tier1 = 1;
		/** <i>native declaration : discord_game_sdk.h:95</i> */
		public static final int DiscordPremiumType_Tier2 = 2;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:98</i><br>
	 * enum values
	 */
	public static interface EDiscordImageType {
		/** <i>native declaration : discord_game_sdk.h:99</i> */
		public static final int DiscordImageType_User = 0;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:102</i><br>
	 * enum values
	 */
	public static interface EDiscordActivityType {
		/** <i>native declaration : discord_game_sdk.h:103</i> */
		public static final int DiscordActivityType_Playing = 0;
		/** <i>native declaration : discord_game_sdk.h:104</i> */
		public static final int DiscordActivityType_Streaming = 1;
		/** <i>native declaration : discord_game_sdk.h:105</i> */
		public static final int DiscordActivityType_Listening = 2;
		/** <i>native declaration : discord_game_sdk.h:106</i> */
		public static final int DiscordActivityType_Watching = 3;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:109</i><br>
	 * enum values
	 */
	public static interface EDiscordActivityActionType {
		/** <i>native declaration : discord_game_sdk.h:110</i> */
		public static final int DiscordActivityActionType_Join = 1;
		/** <i>native declaration : discord_game_sdk.h:111</i> */
		public static final int DiscordActivityActionType_Spectate = 2;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:114</i><br>
	 * enum values
	 */
	public static interface EDiscordActivityJoinRequestReply {
		/** <i>native declaration : discord_game_sdk.h:115</i> */
		public static final int DiscordActivityJoinRequestReply_No = 0;
		/** <i>native declaration : discord_game_sdk.h:116</i> */
		public static final int DiscordActivityJoinRequestReply_Yes = 1;
		/** <i>native declaration : discord_game_sdk.h:117</i> */
		public static final int DiscordActivityJoinRequestReply_Ignore = 2;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:120</i><br>
	 * enum values
	 */
	public static interface EDiscordStatus {
		/** <i>native declaration : discord_game_sdk.h:121</i> */
		public static final int DiscordStatus_Offline = 0;
		/** <i>native declaration : discord_game_sdk.h:122</i> */
		public static final int DiscordStatus_Online = 1;
		/** <i>native declaration : discord_game_sdk.h:123</i> */
		public static final int DiscordStatus_Idle = 2;
		/** <i>native declaration : discord_game_sdk.h:124</i> */
		public static final int DiscordStatus_DoNotDisturb = 3;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:127</i><br>
	 * enum values
	 */
	public static interface EDiscordRelationshipType {
		/** <i>native declaration : discord_game_sdk.h:128</i> */
		public static final int DiscordRelationshipType_None = 0;
		/** <i>native declaration : discord_game_sdk.h:129</i> */
		public static final int DiscordRelationshipType_Friend = 1;
		/** <i>native declaration : discord_game_sdk.h:130</i> */
		public static final int DiscordRelationshipType_Blocked = 2;
		/** <i>native declaration : discord_game_sdk.h:131</i> */
		public static final int DiscordRelationshipType_PendingIncoming = 3;
		/** <i>native declaration : discord_game_sdk.h:132</i> */
		public static final int DiscordRelationshipType_PendingOutgoing = 4;
		/** <i>native declaration : discord_game_sdk.h:133</i> */
		public static final int DiscordRelationshipType_Implicit = 5;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:136</i><br>
	 * enum values
	 */
	public static interface EDiscordLobbyType {
		/** <i>native declaration : discord_game_sdk.h:137</i> */
		public static final int DiscordLobbyType_Private = 1;
		/** <i>native declaration : discord_game_sdk.h:138</i> */
		public static final int DiscordLobbyType_Public = 2;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:141</i><br>
	 * enum values
	 */
	public static interface EDiscordLobbySearchComparison {
		/** <i>native declaration : discord_game_sdk.h:142</i> */
		public static final int DiscordLobbySearchComparison_LessThanOrEqual = -2;
		/** <i>native declaration : discord_game_sdk.h:143</i> */
		public static final int DiscordLobbySearchComparison_LessThan = -1;
		/** <i>native declaration : discord_game_sdk.h:144</i> */
		public static final int DiscordLobbySearchComparison_Equal = 0;
		/** <i>native declaration : discord_game_sdk.h:145</i> */
		public static final int DiscordLobbySearchComparison_GreaterThan = 1;
		/** <i>native declaration : discord_game_sdk.h:146</i> */
		public static final int DiscordLobbySearchComparison_GreaterThanOrEqual = 2;
		/** <i>native declaration : discord_game_sdk.h:147</i> */
		public static final int DiscordLobbySearchComparison_NotEqual = 3;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:150</i><br>
	 * enum values
	 */
	public static interface EDiscordLobbySearchCast {
		/** <i>native declaration : discord_game_sdk.h:151</i> */
		public static final int DiscordLobbySearchCast_String = 1;
		/** <i>native declaration : discord_game_sdk.h:152</i> */
		public static final int DiscordLobbySearchCast_Number = 2;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:155</i><br>
	 * enum values
	 */
	public static interface EDiscordLobbySearchDistance {
		/** <i>native declaration : discord_game_sdk.h:156</i> */
		public static final int DiscordLobbySearchDistance_Local = 0;
		/** <i>native declaration : discord_game_sdk.h:157</i> */
		public static final int DiscordLobbySearchDistance_Default = 1;
		/** <i>native declaration : discord_game_sdk.h:158</i> */
		public static final int DiscordLobbySearchDistance_Extended = 2;
		/** <i>native declaration : discord_game_sdk.h:159</i> */
		public static final int DiscordLobbySearchDistance_Global = 3;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:162</i><br>
	 * enum values
	 */
	public static interface EDiscordEntitlementType {
		/** <i>native declaration : discord_game_sdk.h:163</i> */
		public static final int DiscordEntitlementType_Purchase = 1;
		/** <i>native declaration : discord_game_sdk.h:164</i> */
		public static final int DiscordEntitlementType_PremiumSubscription = 2;
		/** <i>native declaration : discord_game_sdk.h:165</i> */
		public static final int DiscordEntitlementType_DeveloperGift = 3;
		/** <i>native declaration : discord_game_sdk.h:166</i> */
		public static final int DiscordEntitlementType_TestModePurchase = 4;
		/** <i>native declaration : discord_game_sdk.h:167</i> */
		public static final int DiscordEntitlementType_FreePurchase = 5;
		/** <i>native declaration : discord_game_sdk.h:168</i> */
		public static final int DiscordEntitlementType_UserGift = 6;
		/** <i>native declaration : discord_game_sdk.h:169</i> */
		public static final int DiscordEntitlementType_PremiumPurchase = 7;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:172</i><br>
	 * enum values
	 */
	public static interface EDiscordSkuType {
		/** <i>native declaration : discord_game_sdk.h:173</i> */
		public static final int DiscordSkuType_Application = 1;
		/** <i>native declaration : discord_game_sdk.h:174</i> */
		public static final int DiscordSkuType_DLC = 2;
		/** <i>native declaration : discord_game_sdk.h:175</i> */
		public static final int DiscordSkuType_Consumable = 3;
		/** <i>native declaration : discord_game_sdk.h:176</i> */
		public static final int DiscordSkuType_Bundle = 4;
	};
	/**
	 * <i>native declaration : discord_game_sdk.h:179</i><br>
	 * enum values
	 */
	public static interface EDiscordInputModeType {
		/** <i>native declaration : discord_game_sdk.h:180</i> */
		public static final int DiscordInputModeType_VoiceActivity = 0;
		/** <i>native declaration : discord_game_sdk.h:181</i> */
		public static final int DiscordInputModeType_PushToTalk = 1;
	};
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_VERSION = (int)2;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_APPLICATION_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_USER_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_IMAGE_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_ACTIVITY_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_RELATIONSHIP_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_LOBBY_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_NETWORK_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_OVERLAY_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_STORAGE_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_STORE_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_VOICE_MANAGER_VERSION = (int)1;
	/** <i>native declaration : discord_game_sdk.h</i> */
	public static final int DISCORD_ACHIEVEMENT_MANAGER_VERSION = (int)1;
	/**
	 * Original signature : <code>EDiscordResult DiscordCreate(DiscordVersion, DiscordCreateParams*, IDiscordCore**)</code><br>
	 * <i>native declaration : discord_game_sdk.h:637</i><br>
	 * @deprecated use the safer method {@link #DiscordCreate(int, io.github.deathbeam.discordgamesdk.DiscordCreateParams, IDiscordCore.ByReference[])} instead
	 */
	@Deprecated
	int DiscordCreate(int version, DiscordCreateParams params, PointerByReference result);
	/**
	 * Original signature : <code>EDiscordResult DiscordCreate(DiscordVersion, DiscordCreateParams*, IDiscordCore**)</code><br>
	 * <i>native declaration : discord_game_sdk.h:637</i>
	 */
	int DiscordCreate(int version, DiscordCreateParams params, ByReference result[]);
}
